"""
PlaybookForge - Splunk SOAR (Phantom) Exporter
Converts CACAO v2.0 playbooks to Splunk SOAR Python script format.

Splunk SOAR playbooks are Python scripts using the phantom.rules API.
This is CODE GENERATION — not data transformation.
"""

from __future__ import annotations

import json
import re
from typing import Any

from ..core.cacao_model import (
    CacaoPlaybook,
    CommandType,
    WorkflowStep,
    WorkflowStepType,
)
from .base import BaseExporter


class SplunkSOARExporter(BaseExporter):
    """Export CACAO playbooks to Splunk SOAR Python script format"""

    @property
    def platform_name(self) -> str:
        return "Splunk SOAR"

    @property
    def platform_id(self) -> str:
        return "splunk_soar"

    @property
    def file_extension(self) -> str:
        return ".py"

    def export(self, playbook: CacaoPlaybook) -> str:
        return self._generate_python(playbook)

    def export_to_dict(self, playbook: CacaoPlaybook) -> dict[str, Any]:
        """Return metadata + script content as dict."""
        return {
            "script": self._generate_python(playbook),
            "metadata": {
                "name": playbook.name,
                "description": playbook.description or "",
                "playbook_type": "automation",
                "_playbookforge_metadata": {
                    "source_format": "cacao-2.0",
                    "source_id": playbook.id,
                    "converter": "PlaybookForge",
                },
            },
        }

    def _generate_python(self, playbook: CacaoPlaybook) -> str:
        """Generate the complete Splunk SOAR Python script."""
        lines: list[str] = []

        # Header
        lines.append('"""')
        lines.append(f"Playbook: {playbook.name}")
        if playbook.description:
            lines.append(f"Description: {playbook.description}")
        lines.append(f"Generated by PlaybookForge from CACAO v2.0")
        lines.append(f"Source ID: {playbook.id}")
        lines.append('"""')
        lines.append("")
        lines.append("import phantom.rules as phantom")
        lines.append("import json")
        lines.append("")
        lines.append("")

        # Get ordered steps
        ordered = playbook.get_steps_in_order()
        action_steps = [
            (sid, step) for sid, step in ordered
            if step.type not in (WorkflowStepType.START, WorkflowStepType.END)
        ]

        # Generate function for each action step
        func_names: dict[str, str] = {}
        for i, (sid, step) in enumerate(action_steps):
            func_name = self._to_func_name(step.name or f"step_{i}")
            func_names[sid] = func_name

        # on_start function
        first_func = func_names.get(action_steps[0][0], "on_finish") if action_steps else "on_finish"
        lines.append("def on_start(container):")
        lines.append(f'    phantom.debug("on_start() called")')
        lines.append(f"    {first_func}(container=container)")
        lines.append("")
        lines.append("")

        # Generate each step function
        for i, (sid, step) in enumerate(action_steps):
            func_name = func_names[sid]
            next_func = None

            # Determine callback
            if i + 1 < len(action_steps):
                next_func = func_names.get(action_steps[i + 1][0])

            if step.type == WorkflowStepType.IF_CONDITION:
                self._generate_decision_func(lines, step, func_name, func_names, action_steps, i)
            elif step.type == WorkflowStepType.ACTION:
                self._generate_action_func(lines, step, func_name, next_func)
            elif step.type == WorkflowStepType.PLAYBOOK_ACTION:
                self._generate_playbook_func(lines, step, func_name, next_func)
            elif step.type == WorkflowStepType.PARALLEL:
                self._generate_parallel_func(lines, step, func_name, func_names)
            else:
                self._generate_action_func(lines, step, func_name, next_func)

        # on_finish function
        lines.append("def on_finish(container, summary):")
        lines.append(f'    phantom.debug("on_finish() called")')
        lines.append("    return")
        lines.append("")

        return "\n".join(lines)

    def _generate_action_func(
        self,
        lines: list[str],
        step: WorkflowStep,
        func_name: str,
        callback: str | None,
    ) -> None:
        """Generate a phantom.act() function."""
        sig = (
            f"def {func_name}(action=None, success=None, container=None, "
            f"results=None, handle=None, filtered_artifacts=None, "
            f"filtered_results=None, custom_function=None):"
        )
        lines.append(sig)
        lines.append(f'    phantom.debug("{func_name}() called")')
        lines.append("")

        if step.description:
            lines.append(f"    # {step.description}")

        # Build parameters
        if step.commands:
            cmd = step.commands[0]
            action_name = self._command_to_action_name(cmd)
            asset = self._command_to_asset(cmd)

            lines.append("    parameters = []")
            if cmd.content:
                lines.append(f"    parameters.append({json.dumps(json.loads(cmd.content) if cmd.content.startswith('{') else {'data': cmd.content})})")
            else:
                lines.append(f'    parameters.append({{"data": ""}})')

            lines.append("")
            callback_str = f", callback={callback}" if callback else ""
            lines.append(
                f'    phantom.act(action="{action_name}", parameters=parameters, '
                f'assets=["{asset}"]{callback_str}, name="{func_name}")'
            )
        else:
            lines.append(f'    phantom.debug("Manual step: {step.name}")')
            if callback:
                lines.append(f"    {callback}(container=container)")

        lines.append("")
        lines.append("")

    def _generate_decision_func(
        self,
        lines: list[str],
        step: WorkflowStep,
        func_name: str,
        func_names: dict[str, str],
        action_steps: list[tuple[str, WorkflowStep]],
        index: int,
    ) -> None:
        """Generate a phantom.decision() function."""
        sig = (
            f"def {func_name}(action=None, success=None, container=None, "
            f"results=None, handle=None, filtered_artifacts=None, "
            f"filtered_results=None, custom_function=None):"
        )
        lines.append(sig)
        lines.append(f'    phantom.debug("{func_name}() called")')
        lines.append("")
        lines.append(f"    # Condition: {step.condition}")
        lines.append("    phantom.decision(")
        lines.append("        container=container,")
        lines.append("        action_results=results,")
        lines.append("        conditions=[")
        lines.append(f'            ["{step.condition or "true"}"]')
        lines.append("        ]")
        lines.append("    )")
        lines.append("")

        # Resolve true/false callbacks
        true_cb = None
        false_cb = None
        if step.on_true and step.on_true in func_names:
            true_cb = func_names[step.on_true]
        if step.on_false and step.on_false in func_names:
            false_cb = func_names[step.on_false]

        if true_cb:
            lines.append(f"    # True branch")
            lines.append(f"    {true_cb}(container=container, results=results)")
        if false_cb and false_cb != true_cb:
            lines.append(f"    # False branch (alternate path)")

        lines.append("")
        lines.append("")

    def _generate_playbook_func(
        self,
        lines: list[str],
        step: WorkflowStep,
        func_name: str,
        callback: str | None,
    ) -> None:
        """Generate a phantom.playbook() call."""
        sig = (
            f"def {func_name}(action=None, success=None, container=None, "
            f"results=None, handle=None, filtered_artifacts=None, "
            f"filtered_results=None, custom_function=None):"
        )
        lines.append(sig)
        lines.append(f'    phantom.debug("{func_name}() called")')
        callback_str = f", callback={callback}" if callback else ""
        lines.append(
            f'    phantom.playbook("{step.playbook_id or "sub_playbook"}", '
            f'container=container{callback_str}, name="{func_name}")'
        )
        lines.append("")
        lines.append("")

    def _generate_parallel_func(
        self,
        lines: list[str],
        step: WorkflowStep,
        func_name: str,
        func_names: dict[str, str],
    ) -> None:
        """Generate parallel execution."""
        sig = (
            f"def {func_name}(action=None, success=None, container=None, "
            f"results=None, handle=None, filtered_artifacts=None, "
            f"filtered_results=None, custom_function=None):"
        )
        lines.append(sig)
        lines.append(f'    phantom.debug("{func_name}() called — parallel execution")')
        if step.next_steps:
            for ns_id in step.next_steps:
                ns_func = func_names.get(ns_id, "on_finish")
                lines.append(f"    {ns_func}(container=container)")
        lines.append("")
        lines.append("")

    def _to_func_name(self, name: str) -> str:
        """Convert step name to valid Python function name."""
        safe = re.sub(r"[^a-zA-Z0-9_]", "_", name.lower().strip())
        safe = re.sub(r"_+", "_", safe).strip("_")
        if safe and safe[0].isdigit():
            safe = f"step_{safe}"
        return safe or "unnamed_step"

    def _command_to_action_name(self, cmd: Any) -> str:
        """Map CACAO command to Splunk SOAR action name."""
        if cmd.type == CommandType.HTTP_API:
            if cmd.command:
                parts = cmd.command.strip().split()
                if len(parts) >= 2:
                    path = parts[-1]
                    segments = [s for s in path.split("/") if s and not s.startswith("{") and not s.startswith("$")]
                    if segments:
                        return "_".join(segments[-2:])
            return "run_query"
        if cmd.type == CommandType.BASH:
            return "execute_program"
        if cmd.type == CommandType.SSH:
            return "execute_program"
        return "run_query"

    def _command_to_asset(self, cmd: Any) -> str:
        """Map CACAO command to Splunk SOAR asset name."""
        if cmd.type == CommandType.HTTP_API:
            return "http"
        if cmd.type in (CommandType.BASH, CommandType.SSH):
            return "ssh"
        return "default"
